"use client";

import { useState } from "react";
import { Loader2, TrendingUp } from "lucide-react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getForecast } from "@/lib/api";

type ForecastData = { historical: { timestamp: string; consumption: number }[]; forecast: { timestamp: string; forecast: number; lower: number; upper: number }[]; trend: string };
export default function ForecastPage() {
  const [horizon, setHorizon] = useState(7); const [data, setData] = useState<ForecastData | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function generate() { setLoading(true); setError(""); try { setData(await getForecast(horizon) as unknown as ForecastData); } catch (value) { setError(value instanceof Error ? value.message : "Forecast could not be generated."); } finally { setLoading(false); } }
  return <div className="space-y-8 p-8"><header><h2 className="text-3xl font-bold tracking-tight">Forecast</h2><p className="mt-2 text-slate-500">A transparent rolling-baseline forecast based on uploaded history.</p></header><Card><CardContent className="flex flex-wrap items-end gap-4 p-6"><label className="text-sm font-medium">Forecast horizon (days)<input type="number" min="1" max="90" value={horizon} onChange={(event) => setHorizon(Number(event.target.value))} className="mt-2 block w-32 rounded-lg border px-3 py-2" /></label><button onClick={() => void generate()} disabled={loading} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 font-medium text-white disabled:opacity-60">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{loading ? "Generating..." : "Generate forecast"}</button></CardContent></Card>{error && <p className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-800">{error}</p>}{data && <><Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-emerald-600" />Trend: {data.trend}</CardTitle></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={[...data.historical.map((item) => ({ timestamp: item.timestamp, historical: item.consumption })), ...data.forecast.map((item) => ({ timestamp: item.timestamp, forecast: item.forecast }))]}><XAxis dataKey="timestamp" hide /><YAxis /><Tooltip /><Line dataKey="historical" stroke="#2563eb" dot={false} /><Line dataKey="forecast" stroke="#059669" strokeWidth={3} strokeDasharray="5 5" dot={false} /></LineChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Predicted values and interval</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Date</th><th className="p-3">Forecast</th><th className="p-3">Expected range</th></tr></thead><tbody>{data.forecast.map((item) => <tr key={item.timestamp} className="border-b"><td className="p-3">{item.timestamp}</td><td className="p-3 font-medium">{item.forecast}</td><td className="p-3">{item.lower} - {item.upper}</td></tr>)}</tbody></table></div></CardContent></Card></>}</div>;
}