"use client";

import { FormEvent, useState } from "react";
import { Loader2, Send } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { askAnalyst } from "@/lib/api";

type Message = { role: "user" | "assistant"; text: string };
const suggestions = ["What was the highest consumption?", "What is the average consumption?", "Are there unusual consumption patterns?", "Give me recommendations to reduce water wastage."];
export default function AnalystPage() { const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(event?: FormEvent, suggested?: string) { event?.preventDefault(); const text = (suggested ?? question).trim(); if (!text || loading) return; setQuestion(""); setError(""); setMessages((current) => [...current, { role: "user", text }]); setLoading(true); try { const response = await askAnalyst(text); setMessages((current) => [...current, { role: "assistant", text: response.answer }]); } catch (value) { setError(value instanceof Error ? value.message : "The analyst is unavailable."); } finally { setLoading(false); } } return <div className="space-y-8 p-8"><header><h2 className="text-3xl font-bold tracking-tight">AI Analyst</h2><p className="mt-2 text-slate-500">Ask questions and receive answers grounded in the uploaded dataset.</p></header><Card><CardHeader><CardTitle>Conversation</CardTitle></CardHeader><CardContent><div className="min-h-72 space-y-4 rounded-lg bg-slate-50 p-4">{messages.length === 0 && <div><p className="text-sm text-slate-500">Try a question:</p><div className="mt-3 flex flex-wrap gap-2">{suggestions.map((item) => <button key={item} onClick={() => void submit(undefined, item)} className="rounded-full border bg-white px-3 py-2 text-sm hover:border-blue-400">{item}</button>)}</div></div>}{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`rounded-lg p-3 ${message.role === "user" ? "ml-8 bg-blue-600 text-white" : "mr-8 bg-white text-slate-700 shadow-sm"}`}><span className="mr-2 text-xs font-semibold uppercase opacity-60">{message.role === "user" ? "You" : "AquaSense"}</span>{message.text}</div>)}{loading && <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Analyzing the uploaded data...</div>}</div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<form onSubmit={submit} className="mt-4 flex gap-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about your water consumption..." className="min-w-0 flex-1 rounded-lg border px-4 py-3" /><button aria-label="Send question" className="rounded-lg bg-blue-600 px-4 text-white"><Send className="h-5 w-5" /></button></form><button onClick={() => setMessages([])} className="mt-3 text-sm text-slate-500 hover:text-slate-800">Clear conversation</button></CardContent></Card></div>; }