import os
import json
from typing import List, Dict, Any
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv

load_dotenv()

class InsightAgent:
    def __init__(self):
        # OpenRouter configuration
        self.api_key = os.environ.get("OPENROUTER_API_KEY", "")
        self.model_name = os.environ.get("OPENROUTER_MODEL", "openai/gpt-4o-mini")
        self.base_url = "https://openrouter.ai/api/v1"
        
        # Initialize the LLM (only if API key is provided, else we handle gracefully)
        if self.api_key:
            self.llm = ChatOpenAI(
                model=self.model_name,
                api_key=self.api_key,
                base_url=self.base_url,
                temperature=0.2 # Low temperature for analytical consistency
            )
        else:
            self.llm = None
            
        self.system_prompt = """You are AquaSense, an expert AI Water Conservation Advisor and Data Analyst.
You will be provided with a user question and a set of JSON evidence generated by statistical tools and ML models.

CRITICAL RULES:
1. NEVER invent numbers, dates, or analytical results. Use ONLY the data provided in the evidence.
2. NEVER claim unsupported causes (e.g., do not say 'Temperature caused increased consumption' unless causal evidence is explicitly provided).
3. NEVER claim a confirmed leak without physical sensor evidence. Use cautious language like "possible leakage" or "anomalous consumption pattern".
4. Clearly distinguish your factual observations from your possible explanations.
5. Mention uncertainty where appropriate.
6. Be concise, highly professional, and easy to understand.
7. Provide actionable water conservation recommendations based strictly on the evidence.

Evidence format: You will receive a JSON string containing the structural findings.
"""
        self.prompt_template = ChatPromptTemplate.from_messages([
            ("system", self.system_prompt),
            ("human", "User Question: {question}\n\nAnalytical Evidence:\n{evidence}")
        ])

    def generate_insight(self, question: str, evidence: List[Dict[str, Any]]) -> str:
        """
        Synthesizes the accumulated statistical evidence into a human-readable response.
        """
        if not self.llm:
            return "OpenRouter API Key not configured. Please add OPENROUTER_API_KEY to your backend/.env file to generate AI insights."
            
        try:
            # Format the evidence compactly
            compact_evidence = json.dumps(evidence, indent=2)
            
            # Create the chain
            chain = self.prompt_template | self.llm
            
            # Execute
            response = chain.invoke({
                "question": question,
                "evidence": compact_evidence
            })
            
            return response.content
        except Exception as e:
            return f"Failed to generate AI insight due to an error: {str(e)}"
