from typing import Dict, Any, Tuple
from app.tools.sql_tool import SQLTool

class SQLAgent:
    def __init__(self):
        self.tool = SQLTool()

    def parse_and_validate(self, generated_sql: str) -> Tuple[bool, str, str]:
        """
        Takes SQL generated by the LLM, cleans it up, and validates it for safety.
        Returns (is_valid, cleaned_sql, error_message)
        """
        # Remove markdown code blocks if present
        clean_sql = generated_sql.replace("```sql", "").replace("```", "").strip()
        
        is_valid, msg = self.tool.validate_sql(clean_sql)
        return is_valid, clean_sql, msg
